#!/bin/sh
# docker-proxy entrypoint: run 3proxy from a mounted config, or render one from env.
set -eu

CFG_MOUNT="/etc/3proxy/3proxy.cfg"
RENDERED="${RENDERED_CFG:-/tmp/3proxy.cfg}"

die() { echo "[entrypoint] ERROR: $*" >&2; exit 1; }

# 1) Mounted config wins and is used verbatim; env is ignored.
if [ -f "$CFG_MOUNT" ]; then
  echo "[entrypoint] Using mounted config: $CFG_MOUNT (env ignored)" >&2
  exec 3proxy "$CFG_MOUNT"
fi

# 2) Render config from environment.
HTTP_PORT="${HTTP_PORT:-3128}"
SOCKS_PORT="${SOCKS_PORT:-1080}"
BIND_ADDR="${BIND_ADDR:-0.0.0.0}"
NSCACHE="${NSCACHE:-65536}"
MAXCONN="${MAXCONN:-200}"
ENABLE_HTTP="${ENABLE_HTTP:-1}"
ENABLE_SOCKS="${ENABLE_SOCKS:-1}"
ANONYMOUS="${ANONYMOUS:-0}"
ALLOW_OPEN="${ALLOW_OPEN:-0}"
ALLOW_CIDR="${ALLOW_CIDR:-}"
PROXY_USER="${PROXY_USER:-}"
PROXY_PASS="${PROXY_PASS:-}"
NAMESERVER="${NAMESERVER:-}"

# --- validation ---
[ -n "$PROXY_PASS" ] && [ -z "$PROXY_USER" ] && die "PROXY_PASS set but PROXY_USER is empty."
[ -n "$PROXY_USER" ] && [ -z "$PROXY_PASS" ] && die "PROXY_USER set but PROXY_PASS is empty."
if [ "$ENABLE_HTTP" != "1" ] && [ "$ENABLE_SOCKS" != "1" ]; then
  die "Both ENABLE_HTTP and ENABLE_SOCKS are disabled; nothing to run."
fi

# --- decide auth mode ---
# strong  : username/password required (ACL also enforced)
# iponly  : no password, access restricted to ALLOW_CIDR source range
# none    : NO access control at all -> deliberate open relay (opt-in)
if [ -n "$PROXY_USER" ]; then
  AUTH_MODE="strong"
elif [ -n "$ALLOW_CIDR" ]; then
  AUTH_MODE="iponly"
elif [ "$ALLOW_OPEN" = "1" ]; then
  AUTH_MODE="none"
else
  die "No access control configured. Choose one:
  - set PROXY_USER + PROXY_PASS for username/password auth, or
  - set ALLOW_CIDR (e.g. 100.64.0.0/10 for Tailscale, 192.168.0.0/16 for LAN) to restrict by source IP, or
  - set ALLOW_OPEN=1 to deliberately run an OPEN relay (dangerous).
Refusing to start as an accidental open relay."
fi

umask 077
{
  echo "# generated by docker-proxy entrypoint $(date -u +%FT%TZ)"
  echo "nscache $NSCACHE"
  [ -n "$NAMESERVER" ] && echo "nserver $NAMESERVER"
  echo "timeouts 1 5 30 60 180 1800 15 60"
  echo "maxconn $MAXCONN"
  echo "log /dev/stdout"
  echo 'logformat "- %t.%. %N.%p %E %U %C:%c %R:%r %O %I %T"'

  case "$AUTH_MODE" in
    strong)
      printf 'users %s:CL:%s\n' "$PROXY_USER" "$PROXY_PASS"
      echo "auth strong"
      ;;
    iponly) echo "auth iponly" ;;
    none)   echo "auth none" ;;
  esac

  # ACL rules (meaningless under 'none', which disables all ACLs)
  if [ "$AUTH_MODE" != "none" ]; then
    if [ -n "$ALLOW_CIDR" ]; then
      echo "allow * $ALLOW_CIDR"
      echo "deny *"
    else
      echo "allow *"
    fi
  fi

  if [ "$ENABLE_HTTP" = "1" ]; then
    if [ "$ANONYMOUS" = "1" ]; then
      echo "proxy -a -i$BIND_ADDR -p$HTTP_PORT"
    else
      echo "proxy -i$BIND_ADDR -p$HTTP_PORT"
    fi
  fi
  [ "$ENABLE_SOCKS" = "1" ] && echo "socks -i$BIND_ADDR -p$SOCKS_PORT"
} > "$RENDERED"

echo "[entrypoint] auth=$AUTH_MODE http=$ENABLE_HTTP:$HTTP_PORT socks=$ENABLE_SOCKS:$SOCKS_PORT anon=$ANONYMOUS allow_cidr=${ALLOW_CIDR:-<none>}" >&2
# Echo the effective config with any password masked.
sed 's/^users \([^:]*\):CL:.*/users \1:CL:***MASKED***/' "$RENDERED" >&2

exec 3proxy "$RENDERED"
