#!/usr/bin/env bash
# start-proxy: launch the HTTP(S)+SOCKS relay inside devkit.
#
#   PROXY_ENGINE=3proxy (default) | gost
#
# 3proxy: full env-driven config (password auth / source-CIDR / opt-in open relay),
#         HTTP on HTTP_PORT and SOCKS on SOCKS_PORT, or a mounted config verbatim.
# gost:   single auto:// listener (HTTP+SOCKS on one port). Set GOST_LISTEN to a
#         full -L string for obfuscation transports (tls/ws/etc); otherwise built
#         from PROXY_USER/PROXY_PASS + HTTP_PORT.
set -euo pipefail

ENGINE="${PROXY_ENGINE:-3proxy}"

case "$ENGINE" in
  gost)
    if [ -n "${GOST_LISTEN:-}" ]; then
      echo "[start-proxy] gost -L $GOST_LISTEN" >&2
      exec gost -L "$GOST_LISTEN"
    fi
    PORT="${HTTP_PORT:-8080}"; BIND="${BIND_ADDR:-0.0.0.0}"
    AUTH=""
    if [ -n "${PROXY_USER:-}" ] && [ -n "${PROXY_PASS:-}" ]; then
      AUTH="${PROXY_USER}:${PROXY_PASS}@"
    fi
    L="auto://${AUTH}${BIND}:${PORT}"
    echo "[start-proxy] gost -L ${L//${PROXY_PASS:-__none__}/****}" >&2
    exec gost -L "$L"
    ;;
  3proxy) : ;;
  *) echo "[start-proxy] ERROR: unknown PROXY_ENGINE='$ENGINE' (use 3proxy|gost)" >&2; exit 2 ;;
esac

# ---------------- 3proxy ----------------
CFG_MOUNT="/etc/3proxy/3proxy.cfg"
RENDERED="${RENDERED_CFG:-/tmp/3proxy.cfg}"
die() { echo "[start-proxy] ERROR: $*" >&2; exit 1; }

if [ -f "$CFG_MOUNT" ]; then
  echo "[start-proxy] Using mounted config: $CFG_MOUNT (env ignored)" >&2
  exec 3proxy "$CFG_MOUNT"
fi

HTTP_PORT="${HTTP_PORT:-3128}"
SOCKS_PORT="${SOCKS_PORT:-1080}"
BIND_ADDR="${BIND_ADDR:-0.0.0.0}"
NSCACHE="${NSCACHE:-65536}"
MAXCONN="${MAXCONN:-200}"
ENABLE_HTTP="${ENABLE_HTTP:-1}"
ENABLE_SOCKS="${ENABLE_SOCKS:-1}"
ANONYMOUS="${ANONYMOUS:-0}"
ALLOW_OPEN="${ALLOW_OPEN:-0}"
ALLOW_CIDR="${ALLOW_CIDR:-}"
PROXY_USER="${PROXY_USER:-}"
PROXY_PASS="${PROXY_PASS:-}"
NAMESERVER="${NAMESERVER:-}"

[ -n "$PROXY_PASS" ] && [ -z "$PROXY_USER" ] && die "PROXY_PASS set but PROXY_USER is empty."
[ -n "$PROXY_USER" ] && [ -z "$PROXY_PASS" ] && die "PROXY_USER set but PROXY_PASS is empty."
if [ "$ENABLE_HTTP" != "1" ] && [ "$ENABLE_SOCKS" != "1" ]; then
  die "Both ENABLE_HTTP and ENABLE_SOCKS are disabled; nothing to run."
fi

if [ -n "$PROXY_USER" ]; then AUTH_MODE="strong"
elif [ -n "$ALLOW_CIDR" ]; then AUTH_MODE="iponly"
elif [ "$ALLOW_OPEN" = "1" ]; then AUTH_MODE="none"
else
  die "No access control configured. Set PROXY_USER+PROXY_PASS, or ALLOW_CIDR to
  restrict by source IP, or ALLOW_OPEN=1 for a deliberate open relay.
  Refusing to start as an accidental open relay."
fi

umask 077
{
  echo "# generated by devkit start-proxy $(date -u +%FT%TZ)"
  echo "nscache $NSCACHE"
  [ -n "$NAMESERVER" ] && echo "nserver $NAMESERVER"
  echo "timeouts 1 5 30 60 180 1800 15 60"
  echo "maxconn $MAXCONN"
  echo "log /dev/stdout"
  echo 'logformat "- %t.%. %N.%p %E %U %C:%c %R:%r %O %I %T"'
  case "$AUTH_MODE" in
    strong) printf 'users %s:CL:%s\n' "$PROXY_USER" "$PROXY_PASS"; echo "auth strong" ;;
    iponly) echo "auth iponly" ;;
    none)   echo "auth none" ;;
  esac
  if [ "$AUTH_MODE" != "none" ]; then
    if [ -n "$ALLOW_CIDR" ]; then echo "allow * $ALLOW_CIDR"; echo "deny *"; else echo "allow *"; fi
  fi
  if [ "$ENABLE_HTTP" = "1" ]; then
    [ "$ANONYMOUS" = "1" ] && echo "proxy -a -i$BIND_ADDR -p$HTTP_PORT" || echo "proxy -i$BIND_ADDR -p$HTTP_PORT"
  fi
  [ "$ENABLE_SOCKS" = "1" ] && echo "socks -i$BIND_ADDR -p$SOCKS_PORT"
} > "$RENDERED"

echo "[start-proxy] 3proxy auth=$AUTH_MODE http=$ENABLE_HTTP:$HTTP_PORT socks=$ENABLE_SOCKS:$SOCKS_PORT anon=$ANONYMOUS allow_cidr=${ALLOW_CIDR:-<none>}" >&2
sed 's/^users \([^:]*\):CL:.*/users \1:CL:***MASKED***/' "$RENDERED" >&2
exec 3proxy "$RENDERED"
